#  ____   __     __  ____     ____                   _                    _ 
# |  _ \  \ \   / / |  _ \   / ___|   ___    _ __   | |_   _ __    ___   | |
# | |_) |  \ \ / /  | |_) | | |      / _ \  | '_ \  | __| | '__|  / _ \  | |
# |  __/    \ V /   |  __/  | |___  | (_) | | | | | | |_  | |    | (_) | | |
# |_|        \_/    |_|      \____|  \___/  |_| |_|  \__| |_|     \___/  |_|
#                                                                             by IdkMan                                                                           

General:
  #Here you can change language of the plugin, currenty supported languages: EN, PL
  #If you want to add your own language just fill messenges_en.yml file and contact with me on spigot @IdkMan
  Language: EN
  #Max size of log
  MaxLogSize: 1000
  
PVP:
  #How long PVP mode should be?
  TimeInPVPMode: 15
  #Turn off *fly* on pvp. The PVP mode will also be turned on if you hit another player from the bow.
  TurnOffFlyOnPVP: true
  #Disable potion invisibility. Does not disable vanish!
  DisableInvisibilityOnPVP: false
  #Should all commands be blocked during PVP?
  BlockAllCommandsOnPVP: false
  #Should we block any teleport, like */tpa accept* or any another 3rd party plugin teleport?
  #(Excluding chorus fruit teleport, and ender pearl teleport)
  BlockAnyKindOfTeleportOnPVP: false
  #Should we block chorus fruit teleport?
  #PS: If *BlockAnyKindOfTeleportOnPVP* option is set to TRUE then this option below will be ignored at all.
  BlockChorusFruitTeleport: true
  #Should we block ender pearl teleport?
  #PS: If *BlockAnyKindOfTeleportOnPVP* option is set to TRUE then this option below will be ignored at all.
  BlockEnderPeralTeleport: true
  #Should player be killed and items dropped on the ground when logging out during PVP?
  KillWhenLogoutOnPVP: true
  #Should we broadcast info to all players, that the player log out during PVP?
  #This option will be ignored if *KillWhenLogoutOnPVP* option is set to FALSE.
  BroadcastPlayerLoggingOnPVP: true

Other:
  #All commands that will be executed in console when player log out during PVP. You can use %player% variable.
  #Commands should be written without a preceding slash "/"
  #Example: - eco set %player% 0
  CommandsExecutedWhenLogoutInPVP: []
  #If *BlockAllCommandsOnPVP* is set to TRUE then option below will be ignored.
  #If *BlockAllCommandsOnPVP* option is set to FALSE you can define below commands that will be blocked during PVP.
  #You don't need to care about case sensitive at all!
  #Example: - tpa MyImaginedPlayer123
  BlockOnlySelectedCommandsOnPVP:
    - tpa
    - tpayes
    - tpyes
    - tpaccept
    - tpadeny
    - tpdeny
    - tp
    - teleport  
Performance:
  #How frequently plugin should check if player is in combat mode?
  #Safe values: 1-20 per sec.
  CombatModeCheckSpeed: 5
  
#Not enough features? Let me know what you want! Write private message to me on spigot @IdkMan
#or describe your problem on discussion page of this plugin.

